### ISSUE TITLE
+2 rust решения

### ISSUE THREAD

**Issue by estin** [proton/highloadcup17_solutions#7]
из https://www.reddit.com/r/rust/comments/6zdvza/my_experience_participating_in_highload_cup_re/

По предфинальному рейтингу https://highloadcup.ru/media/ckeditor/2017/09/02/rating.html

 - 112 место Евгений Татаркин  791.69732 Rust https://github.com/estin/travels-task       (мое)
 - 233 место  Михаил Панков  1516912.58453 Rust https://github.com/mkpankov/rustler (из реддита)

И да, это было здорово )

**Comment by proton** [comment]
Спасибо за внимательность!
